{
  "hash": "238d940ab3f266c5b0c6fe09f0640c44",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Assignment 05\"\nauthor: \"Vicente Martinez\"\ndate: \"2026-02-23\" \nformat:\n  html: default\n  pdf: default\nbibliography: references.bib\n---\n\n# Assignment 04\n## Exploratory Analysis\n\nData source: World Bank World Development Indicators (WDI) [@worldbank2026].\n\n::: {#8394826f .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport numpy as np\n\ndata = pd.read_csv('wdi.csv')\n\nprint(\"\\n=== GDP GROWTH RATE ===\")\nprint(data['gdp_growth_rate'].describe())\nprint(f\"Observations: {len(data)}\")\nprint(f\"Proportion of Increasing GDP: {(data['gdp_growth_rate'].dropna() > 0).sum()/len(data)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=== GDP GROWTH RATE ===\ncount    202.000000\nmean       4.368901\nstd        6.626811\nmin      -28.758591\n25%        2.438593\n50%        4.204431\n75%        6.200000\nmax       63.439864\nName: gdp_growth_rate, dtype: float64\nObservations: 217\nProportion of Increasing GDP: 0.8433179723502304\n```\n:::\n:::\n\n\n::: {#cell-fig-gdp-dist .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Plot of GDP Growth Rate Distribution](quarto_files/figure-html/fig-gdp-dist-output-1.png){#fig-gdp-dist width=585 height=449}\n:::\n:::\n\n\n::: {#9f79c9b2 .cell execution_count=3}\n``` {.python .cell-code}\ndata_plot2 = data.dropna(subset=['measles_immunisation_rate','gdp_per_capita'])\ncorrelation = data_plot2['gdp_per_capita'].corr(data_plot2['measles_immunisation_rate'])\nprint(f\"\\nCorrelation: {correlation:.3f}\")\nprint(f\"Observations: {len(data_plot2)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCorrelation: 0.314\nObservations: 186\n```\n:::\n:::\n\n\n::: {#cell-fig-gdp-measles-scatter .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Relationship between GDP per Capita and Measles Immunisation Rate](quarto_files/figure-html/fig-gdp-measles-scatter-output-1.png){#fig-gdp-measles-scatter width=948 height=564}\n:::\n:::\n\n\n::: {#5ad02e08 .cell execution_count=5}\n``` {.python .cell-code}\ndata_plot3 = data.dropna(subset=['life_expectancy','gdp_per_capita'])\ncorrelation = data_plot3['gdp_per_capita'].corr(data_plot3['life_expectancy'])\nprint(f\"\\nCorrelation: {correlation:.3f}\")\nprint(f\"Observations: {len(data_plot3)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCorrelation: 0.639\nObservations: 197\n```\n:::\n:::\n\n\n::: {#cell-fig-gdp-life-expectancy .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Relationship between GDP per Capita and Life Expectancy](quarto_files/figure-html/fig-gdp-life-expectancy-output-1.png){#fig-gdp-life-expectancy width=949 height=564}\n:::\n:::\n\n\n| Variable                                  | Observations | Mean  | Std. Dev. | Min    | Median | Max   | Correlation |\n| ----------------------------------------- | ------------ | ----- | --------- | ------ | ------ | ----- | ----------- |\n| GDP Growth Rate (%)                       | 202          | 4.37  | 6.63      | -28.76 | 4.20   | 63.44 | —           |\n| Proportion of Countries with Positive GDP | 217          | 0.843 | —         | —      | —      | —     | —           |\n| GDP per Capita vs Immunisation Rate       | 186          | —     | —         | —      | —      | —     | 0.314       |\n| GDP per Capita vs Life Expectancy         | 197          | —     | —         | —      | —      | —     | 0.639       |\n: Table of Key Statistics {#tbl-stats}\n\n\n## Analysis\nFrom the data gathered from the World Bank [@worldbank2026], I was able to perfrom a few analyses.\n\nAs shown in @tbl-stats, the average GDP growth rate across countries is 4.37%, with substantial dispersion given the standard deviation of 6.63. The minimum value of -28.76% highlights extreme economic contractions in some countries.\n\nThe distribution of GDP growth rates is illustrated in @fig-gdp-dist, which shows a right-skewed distribution with several high-growth outliers. The histogram confirms that most countries cluster between 0% and 10% growth.\n\nThe relationship between GDP per capita and measles immunisation is presented in @fig-gdp-measles-scatter. As reported in @tbl-stats, the correlation is 0.314, indicating a moderate positive association. \n\nIn contrast, @fig-gdp-life-expectancy shows a stronger relationship between GDP per capita and life expectancy. The correlation of 0.639 (see @tbl-stats) suggests a substantially stronger link between income levels and longevity outcomes. This follows what has previously been established as seen in Preston's seminal work [@preston1975] and prior research showing that higher income levels are strongly linked to lower mortality and improved health outcomes [@cutler2006].\n\n",
    "supporting": [
      "quarto_files"
    ],
    "filters": [],
    "includes": {}
  }
}